import type { NextPage } from 'next'
import Head from 'next/head'
import UserAnimations from '../../components/UserAnimations'

const Index: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <UserAnimations />
        </div>
    )
}

export default Index
