import type { NextPage } from 'next'
import Head from 'next/head'
import UserInput from '../components/UserInput'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto py-20">
        <UserInput />
      </div>

    </div>
  )
}

export default Home
