import type { NextPage } from 'next'
import Head from 'next/head'
import AddAnimation from '../components/AddAnimation'
import CreateUser from '../components/CreateUser'
import ShowAnimations from '../components/ShowAnimations'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto py-20">
        <div className="grid grid-cols-2 gap-10">
          <div className='space-y-10'>
            <CreateUser />
            <AddAnimation />
          </div>
          <div className=''>
            <ShowAnimations />
          </div>
        </div>
      </div>

    </div>
  )
}

export default Home
